### ISSUE TITLE
Automate data process

### ISSUE THREAD

**Issue by w33ble** [purbon/logstash-eclipse-demo#1]
From the readme:

> Once you have it, you must normalize it a bit before being able to process it easy peasy with Logstash. To do that, you can use the ruby script under the pre directory named `norm.rb`, this scripts accepts a source path and and a target file where it will store all the xmls documents.

> Once normalized, you can load them into elasticsearch by executing logstash like this:

> `cat bugs.xml | ./bin/logstash -f bugzilla.conf`

Since ruby is a requirement anyway, this whole process could be provided as a rake task (or something similar), no?

**Comment by purbon** [comment]
I automated the whole process using vagrant, I guess this makes everything more easy to setup and run my other people.
